### PR TITLE
Add `textCase` option.

### PR DESCRIPTION
**Pull request by nickclaw**
Thought I'd throw this out there. It may be helpful to some people who want their attributes and tags to have consistent casing.

### CODE REVIEW

**Comment by felixcrive** [comment]
@nickclaw that's a nice improve!

**Comment by nickclaw** [comment]
Pinging @oozcitak :)

I also noticed this could be a fix for #49

**Comment by oozcitak** [comment]
I noticed that [`lodash/lowerCase`](https://lodash.com/docs#lowerCase) and [`lodash/upperCase`](https://lodash.com/docs#upperCase) insert spaces between words, e.g. `-foo-bar` becomes `foo bar`. Since this is not what we want, I replaced those: https://github.com/oozcitak/xmlbuilder-js/compare/nickclaw-master. Please let me know what you think.

**Comment by nickclaw** [comment]
Looks good to me!

**Pull request merged**
